# Setup
title:               tesserae
tagline:             'more than the sum of my parts'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://mountzionryan.github.io/
baseurl:             ''
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              Ryan  Shelton
  twitter:               https://twitter.com/mountzionryan
 email:       http://www.google.com/recaptcha/mailhide/d?k=01p6IF15D1YX3AHhrjkPVExA==&c=hmML5jNmWSS71wzkTm83UjH7fQX3qeFVd96bAhRGcJc=
 description: 'A noetic designer, writer, problem-solver edging toward wisdom.'
   gravatar: 1ab31f46b428111b44df69a28cadd385 # md5 hash of your email address
   
# Custom vars
version:             1.0.0
