# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               tesserae
tagline:             'more than the sum of my parts'
description:         '(<img src="/public/logo.jpg"> <br /> a place for my things <br />
Noetic designer/writer/problem-solver '
url:                 https://mountzionryan.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mountzionryan
  url:               https://twitter.com/mountzionryan
  email:             http://www.google.com/recaptcha/mailhide/d?k=01p6IF15D1YX3AHhrjkPVExA==&c=hmML5jNmWSS71wzkTm83UjH7fQX3qeFVd96bAhRGcJc=

# Custom vars
version:             1.0.0